import Head from 'next/head'
import {Banners} from '@/banners/types'

import {Container} from 'semantic-ui-react'
import {getRundowns} from "@/banners/rundown";
import getVersionParts from "@/banners/version";
import React, {useState} from "react";
import BannerRundownComponent from "@/components/BannerRundown";
import BannerOptionsComponent from "@/components/BannerOptions";


export async function getStaticProps() {
    return {
        props: {
            banners: require('@/data/banners.json')
        },
    };
}

type Properties = {
    banners: Banners
}

export default function Home({banners}: Properties) {
    const [limitedOnly, setLimitedOnly] = useState(true)
    const [sortBy, setSortBy] = useState(null)
    const [order, setOrder] = useState(null)

    return (
        <>
            <Head>
                {/*<title>Create Next App</title>*/}
                {/*<meta name="description" content="Generated by create next app" />*/}
                {/*<meta name="viewport" content="width=device-width, initial-scale=1" />*/}
                {/*<link rel="icon" href="/favicon.ico" />*/}
            </Head>
            <Container style={{marginTop: '2em'}}>
                <BannerOptionsComponent showLimitedOnly={false} limitedOnly={limitedOnly} setLimitedOnly={setLimitedOnly}
                                        order={order} setOrder={setOrder}
                                        sortBy={sortBy} setSortBy={setSortBy}
                />
            </Container>
            <Container style={{overflowX: 'scroll'}}>
                <BannerRundownComponent bannerType={'weapons'}
                                        versionParts={getVersionParts(banners.weapons['4'])}
                                        rundown={getRundowns(banners.weapons['4'])}
                                        limitedOnly={limitedOnly}
                                        order={order}
                                        sortBy={sortBy}
                />
            </Container>
        </>
    )
}
