import Head from 'next/head'
import {FeaturedHistory} from '@/banners/types'
import React from "react";
import HistoryPage from "@/components/history/HistoryPage";
import _ from 'lodash';
import YAML from "yaml";
import fs from "fs";
import path from "path";


export async function getStaticProps() {
    return {
        props: {
            featuredList: _.chain(YAML.parse(fs.readFileSync(path.resolve('./public/data/banners.yaml'), 'utf8')).fiveStarWeapons)
                .map((featured) => _.omit(featured, 'dates'))
                .value(),
        },
    };
}

type Properties = {
    featuredList: FeaturedHistory[]
}

export default function FiveStarWeaponsHome({featuredList}: Properties) {
    return (
        <>
            <Head>
                <title>5&#x2605; Weapon Banner History - Samsara</title>
                {/*<meta name="description" content="Generated by create next app" />*/}
                {/*<meta name="viewport" content="width=device-width, initial-scale=1" />*/}
                {/*<link rel="icon" href="/favicon.ico" />*/}
            </Head>
            <HistoryPage bannerType={'weapons'}
                         title={<>5&#x2605; Weapon Banner History</>}
                         featuredList={featuredList}
            />
        </>
    )
}
