import Head from 'next/head'
import {Banners} from '@/banners/types'

import {Container, Image,} from 'semantic-ui-react'
import {getRundowns} from "@/banners/rundown";
import getVersionParts from "@/banners/version";
import React from "react";
import BannerRundownComponent from "@/components/BannerRundown";


export async function getStaticProps() {

    return {
        props: {
            banners: require('@/data/banners.json')
        },
    };
};

type HomeProperties = {
    banners: Banners
}

export default function BannerComponent({banners}: HomeProperties) {

    return (
        <>
            <Head>
                {/*<title>Create Next App</title>*/}
                {/*<meta name="description" content="Generated by create next app" />*/}
                {/*<meta name="viewport" content="width=device-width, initial-scale=1" />*/}
                {/*<link rel="icon" href="/favicon.ico" />*/}
            </Head>
            <Container style={{marginTop: '3em', overflowX: 'scroll'}}>

                <BannerRundownComponent bannerType={'characters'}
                               versionParts={getVersionParts(banners.characters['5'])}
                               rundown={getRundowns(banners.characters['5'])} />
            </Container>
        </>
    )
}
