import Head from 'next/head'
import {Banners} from '@/banners/types'

import {
    Container,
    Header,
    Table,
} from 'semantic-ui-react'
import getVersionParts from "@/banners/versions";


export const getServerSideProps = async () => {

    return {
        props: {
            banners: require('@/data/banners.json')
        },
    };
};

type HomeProperties = {
    banners: Banners
}


export default function Home({banners}: HomeProperties) {
    // console.log(getVersionParts(banners.characters["5"]))
    return (
        <>
            <Head>
                {/*<title>Create Next App</title>*/}
                {/*<meta name="description" content="Generated by create next app" />*/}
                {/*<meta name="viewport" content="width=device-width, initial-scale=1" />*/}
                {/*<link rel="icon" href="/favicon.ico" />*/}
            </Head>
            <Container text style={{marginTop: '7em', overflowX:'scroll'}}>
                <Table definition className={'history'}>
                    <Table.Header>
                        <Table.Row>
                            <Table.HeaderCell className={'no-border'}/>
                            <Table.HeaderCell>Runs</Table.HeaderCell>
                            {getVersionParts(banners.characters["5"]).map(function (vp, idx) {
                                return (
                                    <Table.HeaderCell colSpan={vp.parts} key={idx}>{vp.version}</Table.HeaderCell>
                                )
                            })}
                        </Table.Row>
                    </Table.Header>

                    {/*<Table.Body>*/}
                    {/*    <Table.Row>*/}
                    {/*        <Table.Cell>Kamisato Ayato</Table.Cell>*/}
                    {/*        <Table.Cell>5</Table.Cell>*/}
                    {/*        <Table.Cell>Image</Table.Cell>*/}
                    {/*        <Table.Cell>15</Table.Cell>*/}
                    {/*        <Table.Cell>14</Table.Cell>*/}
                    {/*        <Table.Cell>13</Table.Cell>*/}
                    {/*    </Table.Row>*/}
                    {/*</Table.Body>*/}
                </Table>
            </Container>
        </>
    )
}
