name: Reload All Data
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 16 15 3,6,9,12 *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull Genshin Impact Banner Data
        uses: benlei/samsara-tools@v2.0
        with:
          game: gi
          output: ../public/data/banners.yaml
          output-image-dir: ../public/images/
          force: true
          min-data-size: 70000

      - name: Pull HSR Banner Data
        uses: benlei/samsara-tools@v2.0
        with:
          game: hsr
          output: ../public/data/hsr-banners.yaml
          output-image-dir: ../public/images/
          force: true
          min-data-size: 25000

      - name: Get the file diff in public
        run: |
          echo "diff_lines=$(git diff --stat HEAD  -- public/ | wc -l | awk '{$1=$1};1')" >> $GITHUB_ENV

      - name: Push new data
        if: env.diff_lines != '0'
        run: |
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/
          git commit -m "generated: full data reload"
          git push
          sleep 5

    outputs:
      diff_lines: ${{ env.diff_lines }}

  deploy:
    needs: update
    if: needs.update.outputs.diff_lines != '0'
    uses: ./.github/workflows/workflow.yaml
    secrets: inherit
