name: Samsara Workflow
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'main'
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md' # ignore docs, they don't contribute to the build process
      - '.github/workflows/force_update_data.yaml' # ignore the force update workflow
      - '.github/workflows/update_data.yaml' # ignore the update workflow

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v4
        with:
          # workflow_call inherits parent event name - either way, should only occur on main branch
          ref: ${{ (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && 'main' || '' }}

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: unit tests
        run: pnpm test

      - name: build static pages
        run: pnpm build

  deploy:
    if: github.ref_name == 'main' && (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
    needs: 'build'
    runs-on: ubuntu-latest
    name: Deploy
    environment: production
    steps:
      - name: Trigger Deploy Hook
        run: |
          curl -X POST "${{ secrets.CLOUDFLARE_HOOK }}" | grep success | grep true
